import { SessionEventType, GOAL_COMPLETION_VERIFICATION_QUERY_SOURCE, createChildTraceContext, failOpenGoalCompletionVerification, failedGoalCompletionVerification, formatGoalCompletionVerificationPrompt, parseGoalCompletionVerificationText, runWithModelInvocationContext, traceContextToLogContext, } from "../deps.js";
import type { GoalCompletionVerificationOutput, Model, SessionEvent, SessionGoal, TraceContext, } from "../deps.js";
import { buildRuntimeProviderRequestMessages, throwIfTurnAborted } from "../helpers/index.js";
import { projectMessagesForModelMediaPolicy } from "../helpers/media-budget.js";
import type { AgentRuntimeInternal } from "../internal.js";
import { isRuntimeAttachmentEntry, type RuntimeMessageEntry } from "../../agent/message-history.js";
import { createRefreshRuntimeHeadersBeforeModelAttempt } from "./model-runtime-headers.js";
import { resolveModelRequestSessionTypeFromTaskType } from "./model-request-session-type.js";
import { createRuntimeModel } from "./runtime-model.js";
import { isStartPlanBusyStreamRecoveryFailure } from "./streaming-recovery.js";
import { recordModelUsageFact } from "./usage-observability.js";
import { runTargetCompletionVerificationWithTelemetry } from "./target-completion-verification-telemetry.js";
