import { createPartId, traceContextToLogContext, TurnMachineImpl } from "../deps.js";
import type { MessageId, ModelToolCall, ToolCallId, TraceContext, ToolCall, ToolExecutionResult, } from "../deps.js";
import { createStreamRecoveryAnchorId, emitStreamRecoveryAnchor, emitStreamingToolLedgerUpdate, isErrorForToolResult, isTurnCancellationError, modelContentForToolResult, stringifyToolResultOutput, toRecordInput, } from "../helpers/index.js";
import { persistToolResultMediaAttachments } from "../helpers/tool-result-media-persistence.js";
import type { RuntimeModelTextResult, StreamedToolExecutionResult } from "../types.js";
import type { AgentRuntimeInternal } from "../internal.js";
import { emitSyntheticStreamedToolError } from "./streaming-tool-synthetic-result.js";
import { persistPendingToolPart, projectToolNameForNonEmptyBoundary, } from "./tool-part-persistence.js";
import { persistToolModelStepFinish } from "./turn-step-finish.js";
import { completedToolPartMetadata, mcpToolPartMetadata } from "./tool-part-metadata.js";
import { drainInlineGuideForNextRequest } from "./turn-guide-drain.js";
import { handleToolCallAnomalyWarnings } from "./turn-tool-warnings.js";
import { emitNestedModelUsageEvents } from "./turn-nested-model-usage.js";
import type { RegularTurnLoopState } from "./turn-loop-state.js";
import { isAutomationMutationRestrictedTurn, isOffPeakCreateRestrictedTurn, recordCompletedToolBatch, } from "./turn-loop-state.js";
import { recordToolUsageFromResult } from "./turn-tool-usage.js";
import { recordBrowserTurnToolResult } from "../../repl/browser-turn-state.js";
import { createRuntimeToolResultEntry } from "../../agent/message-history.js";
import { commitTurnRequestEntries } from "./turn-output-token-continuation.js";
