import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
const core='/workspace/knorvia-studio/apps/cli/packages/core',hash=x=>createHash('sha256').update(x).digest('hex'),names=['message-persistence','events','workspace-checkpoints'],data=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const bind=s=>s.replace(/from "([^"]+)"/gu,(_,p)=>`from ${JSON.stringify(p.startsWith('.')?'file://'+core+'/dist/runtime/methods/'+p:import.meta.resolve(p))}`);
const old={};for(const n of names){const b=JSON.parse(await fs.readFile(core+'/test/runtime-'+n+'-baseline-20261003.json','utf8')),f=b.files[n];for(const k of ['source','compiled','declaration'])assert.equal(hash(f[k]),f[k+'Sha256']);old[n]=await import(data(bind(f.compiled)))}
async function observe(o){const trace={traceId:'owned-trace'},calls=[],input={canonical:true},signal=new AbortController().signal,clock=Date.now;Date.now=()=>11;try{
const port={async promoteSessionInput(x){assert.equal(this,port);calls.push('promote');assert.equal(x.parts.length,1);assert.equal(x.message.metadata.inputIntent,intent)},async saveMessage(){calls.push('unexpected-message')},async savePart(){calls.push('unexpected-part')}},intent={kind:'sendText',text:'Owned',sourceCommandId:'command'};
const runtime={sessionStore:port,sessionId:'owned',config:{},getTools:()=>[],getSessionModelSelection:()=>undefined,createEvent(type,payload,t){assert.equal(t,trace);return{type,payload}},async appendEvent(event,t){assert.equal(t,trace);calls.push('promoted-event');assert.equal(event.payload.sourceCommandId,'command')},async persistMessage(){calls.push('unexpected-message')},async persistPart(){calls.push('unexpected-part')}};
await o['message-persistence'].persistUserPrompt.call(runtime,'owned-message','Owned',undefined,trace,{sessionInputId:'owned-input',intent});assert.deepEqual(calls,['promote','promoted-event']);
const saved={id:'stored',sessionId:'owned',type:'turn.steerQueued',timestamp:new Date(12),sequenceNumber:4,payload:{pendingInputId:'owned-input',input:'Owned'}},ledgerFailure=Error('Owned ledger failure'),events=[];
// Enum values are supplied by the unchanged contract dependency, not guessed.
const deps=await import('file://'+core+'/dist/runtime/deps.js');saved.type=deps.SessionEventType.TurnSteerQueued;
const eventRuntime={sessionId:'owned',eventStore:{async append(e){events.push('store');return saved}},sessionStore:{async saveSessionInput(x){assert.equal(x.id,'owned-input');events.push('ledger');throw ledgerFailure}},logger:{warn(label,fields){assert.equal(fields.errorMessage,ledgerFailure.message);events.push('warn')}},async notifyEventSinks(e,t){assert.equal(e,saved);assert.equal(t,trace);events.push('sink')}};
await o.events.appendEvent.call(eventRuntime,{type:'owned',payload:input},trace);assert.deepEqual(events,['store','ledger','warn','sink']);
const copyCalls=[],copyFailure=Error('Owned part failure'),message={info:{id:'parent',sessionID:'owned',role:'user',time:{created:1}},parts:[{id:'part',sessionID:'owned',messageID:'parent',type:'text',text:'Owned'}]},copyRuntime={sessionStore:{},async persistMessage(m,t,source){assert.equal(t,trace);assert.deepEqual(source,{sessionID:'owned',id:'parent'});assert.notEqual(m.id,'parent');copyCalls.push('message')},async persistPart(p,t,source){assert.equal(t,trace);assert.deepEqual(source,{sessionID:'owned',id:'part'});copyCalls.push('part');throw copyFailure}};
await assert.rejects(o['workspace-checkpoints'].copySessionMessagesForFork.call(copyRuntime,{forkedSessionId:'child',messages:[message,message],traceContext:trace}),e=>e===copyFailure);assert.deepEqual(copyCalls,['message','part']);return{calls,events,copyCalls}}finally{Date.now=clock}}
const expected=await observe(old);console.log(JSON.stringify({mode:'frozen-baseline',expected,groups:3}));
