import { TurnMachineImpl, createPartId } from "../deps.js";
import type { MessageId, Model, ModelToolCall, ToolCall, ToolCallId, TraceContext, } from "../deps.js";
import { emitStreamingToolLedgerUpdate, requireRuntimeToolCallName, toRecordInput, throwIfTurnAborted, } from "../helpers/index.js";
import type { AgentRuntimeInternal } from "../internal.js";
import type { StreamedToolExecutionResult } from "../types.js";
import { createSyntheticStreamedToolResult } from "./streaming-tool-synthetic-result.js";
import { beginStreamRecoveryAttempt, emitStreamRecoveryRetryEvents, emitStreamRecoveryStarted, hasStreamRecoveryBudget, recoverPartialAssistantOutputFailure, } from "./streaming-recovery.js";
import { executeToolCallsForModelStep } from "./turn-tools.js";
import { mcpToolPartMetadata } from "./tool-part-metadata.js";
import { persistPendingToolPart } from "./tool-part-persistence.js";
import { isAutomationMutationRestrictedTurn, isOffPeakCreateRestrictedTurn, recordModelHistoryRound, type RegularTurnLoopState, } from "./turn-loop-state.js";
import { createRuntimeAssistantEntry } from "../../agent/message-history.js";
import { commitTurnRequestEntries } from "./turn-output-token-continuation.js";
