from pathlib import Path
import json,re,collections
O=json.loads(Path('licensing/current-files.json').read_text())['files'];o={r['path']:r for r in O}
def prod(p):return p.startswith(('apps/cli/packages/','packages/')) and '/src/'in p and Path(p).suffix in ['.ts','.tsx','.js','.jsx','.mjs','.cjs'] and not any(x in p for x in ['.test.','.spec.','/__tests__/','/evidence/'])
base={}
for l in Path('/tmp/knorvia-progress-base-tree-20261003.txt').read_text().splitlines():
 a,p=l.split('\t',1);s=a.split();base[p]={'sha':s[2],'bytes':int(s[3])if s[3]!='-'else 0}
ledger={p:r for p,r in o.items()if prod(p)};diffs={};new={};removed={};snapshots={}
for n in [8,9,10,11,12]:
 meta=json.loads(Path(f'/tmp/knorvia-progress-pr{n}-20261003.json').read_text());hdoc=json.loads(Path(f'/tmp/knorvia-progress-pr{n}-tree-20261003.json').read_text());assert not hdoc['truncated'];h={r['path']:r for r in hdoc['tree']};mb=json.loads(Path(f'/tmp/knorvia-progress-pr{n}-mergebase-20261003.json').read_text())
 if n in [8,11]:
  bdoc=json.loads(Path(f'/tmp/knorvia-progress-pr{n}-mergebase-tree-20261003.json').read_text());assert not bdoc['truncated'];b={r['path']:r for r in bdoc['tree']}
 else:b=base
 diffs[n]={p for p in h if prod(p)and h[p]['sha']!=b.get(p,{}).get('sha')};new[n]={p for p in diffs[n]if p not in b};removed[n]={p for p in b if prod(p)and p not in h};snapshots[n]={'head':meta['head'],'base':meta['base'],'mergeBase':mb['merge_base_commit'],'draft':meta['draft'],'merged_at':meta['merged_at'],'changedProductionPaths':len(diffs[n]),'newSourceArtifacts':len(new[n]),'removedPaths':len(removed[n])}
u=set.union(*diffs.values());nu=set.union(*new.values());foundation={p for p,r in ledger.items()if r['classification']in ['original','independent-replacement','reviewed-retained']};combined=foundation|u;denom=set(ledger)|u;existing=u&set(ledger)
by=collections.defaultdict(lambda:{'ledger':0,'draftChanged':0,'foundationLabels':0,'labelOrDraft':0})
for p in denom:
 key='/'.join(p.split('/')[:2]);by[key]['ledger']+=p in ledger;by[key]['draftChanged']+=p in u;by[key]['foundationLabels']+=p in foundation;by[key]['labelOrDraft']+=p in combined
weightedDenom=sum(r['bytes']for r in ledger.values());weightedCombined=sum(ledger[p]['bytes']for p in combined&set(ledger));res={'productionFilter':'roots apps/cli/packages or packages, /src/, ts/tsx/js/jsx/mjs/cjs; exclude .test./.spec./__tests__/evidence. Declaration/static/code differences remain uncertainty; no docs/commits counted.','localLedgerDenominator':len(ledger),'localLedgerClassification':dict(collections.Counter(r['classification']for r in ledger.values())),'headUnionDenominatorIncludingNew':len(denom),'uniquePublishedChangedPaths':len(u),'newArtifactUnion':len(nu),'changedPathsInLocalLedger':len(existing),'ledgerOriginalIndependentLabels':len(foundation),'labelAndDraftOverlap':len(foundation&u),'labelOrDraftUnion':len(combined),'labelOrDraftInExistingLedger':len(combined&set(ledger)),'fileCoverageProxyExistingLedger':len(combined&set(ledger))/len(ledger),'fileCoverageProxyExpandedDenom':len(combined)/len(denom),'byteCoverageProxyExistingLedger':weightedCombined/weightedDenom,'perPR':snapshots,'byRoot':dict(by),'paths':{'changed':sorted(u),'foundation':sorted(foundation),'union':sorted(combined),'newArtifacts':sorted(nu),'denominator':sorted(denom)},'parentReportedComparator':{'productionChangedByPR':{8:79,9:123,10:152,11:184,12:42},'union':577,'ledgerDenominator':4077,'classification':{'upstream-modified':2072,'upstream-unchanged':960,'unreviewed':592,'independent-replacement':438,'original':15},'qualification':'Root published snapshot/filter may differ from E local saved ledger; discrepancy retained, do not force agreement or treat any 577 as complete owners.'},'initialComparisonCorrection':'Initial f25b current base-tip comparison rather than PR merge-base yielded484existing/627total changed paths and923/4109 initial proxy; withdrawn. PR8/11 diverged. Initial syntax else0 error corrected before count output, script preserved.'};Path('/tmp/knorvia-progress-corrected-results-20261003.json').write_text(json.dumps(res,indent=2)+'\n');print(json.dumps({k:v for k,v in res.items()if k not in ['paths','byRoot']},indent=2));print(json.dumps(res['byRoot'],indent=2))
