# Local/remote published metadata only; selected source bytes hashed/counted without text/AST/API inspection.
from pathlib import Path
import json,hashlib,subprocess
out=Path('docs/evidence/core-published-ownership-next-screen-20261003');core='apps/cli/packages/core/src/';baseline='0652e224ad49630ec4f46b68d1b2868e03c222e3'
def bind(p):
 b=Path(p).read_bytes();return dict(path=str(p),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
def rows(x):return x if isinstance(x,list) else x.get('files',[])
ledger_path='docs/evidence/core-remaining-screen-20261003/core-metadata-allocation-ledger.json';ledger=json.loads(Path(ledger_path).read_text());entries={r['path']:r for r in ledger['entries']};origin_path='licensing/current-files.json';review_path='licensing/reviews.json';origin={r['path']:r for r in rows(json.loads(Path(origin_path).read_text()))};reviews=rows(json.loads(Path(review_path).read_text()))
a_api=[json.loads(x)for x in Path('/tmp/knorvia-a-pr11-paths-20261003.jsonl').read_text().splitlines()];e_api=[json.loads(x)for x in Path('/tmp/knorvia-e-pr8-paths-20261003.jsonl').read_text().splitlines()];a_initial=set(r['filename']for r in a_api if r['filename'].startswith(core));e_current=set(r['filename']for r in e_api if r['filename'].startswith(core));a_previous=set(r['previous_filename']for r in a_api if r.get('previous_filename') and r['previous_filename'].startswith(core))
a_head=json.loads(Path('/tmp/knorvia-a-pr11-core-tree-pinned-20261003.json').read_text());a_base=json.loads(Path('/tmp/knorvia-a-pr11-base-core-tree-20261003.json').read_text());assert not a_head['truncated'] and not a_base['truncated'];base_tree={r['path']:r for r in a_base['tree']};head_tree={r['path']:r for r in a_head['tree']};a_pinned=set(p for p in set(base_tree)|set(head_tree) if base_tree.get(p)!=head_tree.get(p));a_reserved=a_initial|a_pinned|a_previous
ownership=dict(pr11={'url':'https://github.com/accomplish07zrh-eng/knorvia-studio/pull/11','headBeforePathFetch':'37b5890b0b5eeaab969b711c77cdd9d621ab2549','pinnedHeadAfter':'0a36f716872e70be1d10672bba24824dd2e22a7d','base':'f25b931164ee6287167e965e9da7a7586131b264','reportedChangedFiles':1842,'firstChangedCorePaths':sorted(a_initial),'pinnedCoreTreeChangedPaths':sorted(a_pinned),'unionReservedCorePaths':sorted(a_reserved),'qualification':'Head race preserved; exact pinned published Git-tree metadata compared without content fetch. Conservative union of initial list/pinned diff/previous names used as exclusions. Snapshots are not future-head/current ongoing-work acceptance.'},pr8={'url':'https://github.com/accomplish07zrh-eng/knorvia-studio/pull/8','head':baseline,'base':'f25b931164ee6287167e965e9da7a7586131b264','reportedChangedFiles':1542,'changedCorePaths':sorted(e_current),'qualification':'Snapshot current E source candidates preserved, not rights acceptance.'},treeMetadata={'base':bind('/tmp/knorvia-a-pr11-base-core-tree-20261003.json'),'pinnedHead':bind('/tmp/knorvia-a-pr11-core-tree-pinned-20261003.json'),'baseTruncated':False,'headTruncated':False,'baseCorePaths':len(base_tree),'headCorePaths':len(head_tree)})
(out/'published-ownership-snapshot.json').write_text(json.dumps(ownership,indent=2)+'\n')
# Preserve only metadata, no A source/config/private checkpoint recovery or cross-lane import.
for src,name in [('/tmp/knorvia-a-pr11-core-tree-pinned-20261003.json','a-pr11-pinned-core-tree.json'),('/tmp/knorvia-a-pr11-base-core-tree-20261003.json','a-pr11-base-core-tree.json')]:
 (out/name).write_bytes(Path(src).read_bytes())
prior=json.loads(Path('docs/evidence/core-remaining-screen-20261003/selected-ledger.json').read_text());retained={r['path']:r for r in prior['records']};dynamic=json.loads(Path('docs/evidence/core-model-context-session-owner-packet-20261003/reservation.json').read_text());retained.update({r['path']:r for r in dynamic['inventory'] if r.get('decision')=='retained; not rewritten'})
independent={p for p,r in origin.items() if p.startswith(core) and r.get('classification')=='independent-replacement'};author_candidate=set();manifest_bindings=[]
for f in subprocess.check_output(['rg','--files','docs/evidence','-g','curator-draft-manifest.json'],text=True).splitlines():
 d=json.loads(Path(f).read_text());file_rows=d.get('files',[]);file_rows=list(file_rows.values()) if isinstance(file_rows,dict) else file_rows
 for r in file_rows:
  if isinstance(r,dict) and r.get('target','') and r['target'].startswith(core):author_candidate.add(r['target']);manifest_bindings.append(dict(path=r['target'],sha256=r.get('sha256'),manifest=f))
questions=[(core+'tool/handlers/tool-perf.ts','134-line diagnostics/performance handler name only. Root must confirm whether presentation/input owner is separable from A runtime instrumentation and G/native benchmarking/execution. No E allocation or pure formatter inference.'),(core+'tool/handlers/todo.ts','198-line stateful task-list handler name only. Root must assign state/service authority before work; not assumed E projection scope. Published-path absence does not release ongoing A ownership.')]
retained_names=[core+'mcp/result-format.ts',core+'context/dynamic-sections.ts',core+'system-reminder/source.ts'];protected_names=[core+'hooks/configured-runner-input.ts'];selected=[p for p,_ in questions]+retained_names+protected_names
files=[f for f in subprocess.check_output(['rg','--files','docs/evidence','licensing/evidence','-g','*.json'],text=True).splitlines() if not f.startswith(str(out)+'/')];hits={p:[] for p in selected}
for f in files:
 text=Path(f).read_text()
 for p in selected:
  if p in text:hits[p].append(dict(**bind(f),role='Metadata reference; classify explicit retained/reservation below, no new owner receipt located.'))
def selected_row(p):
 b=Path(p).read_bytes();assert b==subprocess.check_output(['git','show',baseline+':'+p]);r=entries[p];o=origin[p];h=bind(p);assert h['sha256']==r['sha256'] and h['bytes']==r['bytes'];return dict(**h,lines=b.count(b'\n'),existingLedgerExact=True,origin=o,globalReviewHits=[x for x in reviews if x.get('path')==p],ledgerExactPriorSourceRecords=r['exactPriorSourceRecords'],ledgerOlderOrDifferentSourceRecordCount=r['olderOrDifferentSourceRecordCount'],ledgerAllocation=r['allocation'],pr11ChangedPath=p in a_reserved,pr8ChangedPath=p in e_current,existingAuthorCandidate=p in author_candidate,metadataReceiptHits=hits[p])
inquiries=[]
for p,q in questions:
 r=selected_row(p);assert not r['pr11ChangedPath'] and not r['pr8ChangedPath'] and not r['existingAuthorCandidate'] and p not in independent;assert not r['globalReviewHits'] and not r['ledgerExactPriorSourceRecords'];r.update(ownershipQuestion=q,status='Conditional routing inquiry ONLY; NOT an eligible/allocated E owner');inquiries.append(r)
retained_rows=[]
for p in retained_names:
 r=selected_row(p);r.update(priorExactRetainedDecision=retained[p].get('decision'),reason=retained[p].get('reason'),priorDecisionEvidence='core-model-context-session-owner-packet-20261003/reservation.json' if '/context/'in p else 'core-remaining-screen-20261003/selected-ledger.json',status='RETAIN; not promoted or force-reauthored based on size/receipt absence');retained_rows.append(r)
protected_rows=[]
for p in protected_names:
 r=selected_row(p);assert 'protected A/'in r['ledgerAllocation'];r['status']='EXCLUDE existing A runtime/permission/trust reservation even absent from PR11 changed paths';protected_rows.append(r)
old= json.loads(Path('docs/evidence/core-tool-next-allocation-shortlist-20261003/shortlist.json').read_text());holds=old['rootReportedReconciliation'];holds['graphFoldBounds']={'evidence':'graph-display-expression-20261002.json','localFold':'ed9f00051bdea60751f2f86191c4c83076f02c7d52d96c6ae8485ca2b9726487','rootFold':'89d83bcce02667f800f3b409475f7812a1b8b9d495878af4da74362e17adfdd4','localBounds':'7c5da335dd06647654013e8950c1b1644ccfc1039d8221cbdb6107c4b411a8df','rootBounds':'df3076e726eddd682e529c9907eb699476176d60092c37a0765bc4fbde7606bd','status':'Known accepted root technical HOLD for final combination, no import/reauthor or whole-file MIT acceptance.'}
result=dict(baseline=baseline,branch='parallel/material-closure-fast-20261002',metadataInputs=[bind(ledger_path),bind(origin_path),bind(review_path),bind('docs/evidence/core-remaining-screen-20261003/selected-ledger.json'),bind('docs/evidence/core-model-context-session-owner-packet-20261003/reservation.json')],eligibleEWholeOwnerShortlist=[],eligibleECount=0,conditionalRoutingInquiries=inquiries,retainedExactDecisions=retained_rows,protectedAExclusion=protected_rows,publishedOwnershipEvidence=bind(out/'published-ownership-snapshot.json'),excludedCounts={'pr11CoreUnion':len(a_reserved),'pr8Core':len(e_current),'independentCore':len(independent),'independentTool':sum('/tool/'in p for p in independent),'existingAuthorCandidateCore':len(author_candidate)},excludedExistingAuthorCandidatePaths=sorted(author_candidate),retainedRootHashHolds=holds,otherHolds='Registry ac09(local)/12a18abd(root) and read-state1b4(local)/5ac(root), summary/format-roster/graph exact hash holds unchanged; parent accepted reports only, no private root access/reauthor/import.',rootRecoveryBoundary='Root PR12dd963aae58aa6111e5c65532c30c152c040de30a parent-reported intact. Unavailable private checkpoint/Library-scope denial left untouched: no alternate extraction, credentials, private files, recovery/source import; root owns its network draft.',noSourceBodyApiAstReview=True,noAuthorCycles=True,noTestsBuildsRuntimeOrGlobalLicensing=True,materialObligationsOpen=21,qualification='Remaining name/size inquiries are not allocation/eligibility or rights proof. Existing612core metadata reused; bounded selected hash/count IO only. No fresh source bodies/helper/API extraction, source-emitted matrix, actual workflow/tool/provider/user data/native/network configuration. Prior curator source exposure of retained records/historical broader exposures/repaired scratch breach qualified; metadata absence not release of lane ownership. SavedSol/high/Fast unchanged/unverified, no OS isolation/access audit. No new unallocated work.',passed=True)
(out/'screen-results.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'eligibleE':0,'conditionalRouting':[{'path':r['path'],'sha256':r['sha256'],'lines':r['lines'],'hits':len(r['metadataReceiptHits'])}for r in inquiries],'retained':retained_names,'excludedCounts':result['excludedCounts']},indent=2))
