import { beginLocalTurnPreparation, type LocalTtftDetail } from "@knorvia/contracts";
import { runtimeInputMetadata } from "../../agent/runtime-input-presentation.js";
import { CoreErrorType, HookEventName, SessionEventType, createChildTraceContext, createQueryId, createModelUsageSummaryFromEvents, createMessageId, createTurnId, runWithContextAsync, traceContextToLogContext, TurnMachineImpl, formatLocalIsoDate, } from "../deps.js";
import type { HookRunResult, MessageId, MessagePart, QueryId, SessionEvent, SessionGoal, TurnState, } from "../deps.js";
import { parseCompactCommand, parseRewindCommand, createTurnAbortScope, throwIfTurnAborted, createTurnFailureError, isTurnCancellationError, appendTurnOutcomeEvent, buildDateChangeReminderBody, buildRuntimeUserEntriesFromTurn, buildUserContentFromTurn, logResolvedTurnAttachments, resolveTurnAttachments, summarizeTurnAttachmentsForEvent, runtimeMetadataForSyntheticUserMessageSource, } from "../helpers/index.js";
import type { ActiveTurnSteeringState, ExecuteTurnOptions, TurnResult } from "../types.js";
import type { ActiveTurnStartReservation } from "../types.js";
import type { AgentRuntimeInternal } from "../internal.js";
import { createRuntimeCommandId } from "../command-queue.js";
import type { PromptRuntimeCommand } from "../command-queue.js";
import { enqueueCancellableRuntimeCommand } from "./runtime-command-submit.js";
import { buildReferencedSessionContextReminderBody } from "../../session-context/read-session-context.js";
import { runRegularTurnLoop } from "./turn-loop.js";
import { maybeStartDeferredSessionTitleGeneration, maybeStartSessionTitleGeneration, } from "./session-title.js";
import type { RegularTurnLoopState } from "./turn-loop-state.js";
import { finishOutputTokenRecovery } from "./turn-output-token-continuation.js";
import { recordTurnUsageFact } from "./usage-observability.js";
import { persistStableForkCompletionBoundary } from "./stable-fork-boundary.js";
import { closeGoalStateChangeReminderDeferral, openGoalStateChangeReminderDeferral, } from "./goal-state-reminder.js";
import { scheduleProjectMemoryExtraction } from "../helpers/project-memory-extraction.js";
import { appendBrowserTurnScreenshot } from "./browser-turn-screenshot.js";
import { clearBrowserTurnState } from "../../repl/browser-turn-state.js";
import { endWindowsComputerTurn } from "./windows-computer-turn-end.js";
import { applySubmissionExecutionState, createTurnModel } from "./turn-model.js";
import { rebuildContextPrefix } from "./context-refresh.js";
