interface ObservedRuntimePorts {
  rootTraceContext: TraceContext;
  getSessionModelSelection: () => { providerId: string; modelId: string; options?: { reasoningLevel?: string | undefined; } | undefined; } | undefined;
  config: AgentRuntimeConfig;
  sessionId: SessionId;
  turnNumber: number;
  currentTurnFileChanges: RuntimeTurnFileChangeMap;
  reserveTurnStart: (turnId: TurnId, traceContext: TraceContext, kind: ActiveTurnKind) => void;
  logger: Logger | undefined;
  agentTelemetry: RuntimeTelemetryFacade;
  contextInitialized: boolean;
  ensureContextInitialized: (traceContext: TraceContext, model?: Model | undefined) => Promise<void>;
  runSessionStartHooks: (source: "compact" | "resume" | "clear" | "startup", traceContext: TraceContext, signal?: AbortSignal | undefined, model?: Pick<Model, "providerId" | "modelId"> | undefined) => Promise<HookRunResult>;
  injectHookAdditionalContextIntoMessageHistory: (eventName: HookEventName, additionalContexts: readonly string[]) => RuntimeMessageEntry | undefined;
  executeManualCompact: (input: string, customInstructions: string | undefined, turnId: TurnId, turnTraceContext: TraceContext, abortSignal?: AbortSignal | undefined, inputId?: string | undefined, model?: Model | undefined) => Promise<TurnResult>;
  executeRewindCommand: (input: string, command: ParsedRewindCommand, turnId: TurnId, turnTraceContext: TraceContext, abortSignal?: AbortSignal | undefined, inputId?: string | undefined) => Promise<TurnResult>;
  beginActiveTurn: (turnId: TurnId, traceContext: TraceContext, kind: ActiveTurnKind, steerable: boolean, options?: { inputId?: string | undefined; } | undefined) => ActiveTurnSteeringState;
  ensureSessionPersisted: (input: string, traceContext: TraceContext) => Promise<void>;
  readSessionTargetForContext: (traceContext: TraceContext) => Promise<SessionGoal | null>;
  createEvent: (type: SessionEventType, payload: unknown, traceContext: TraceContext) => SessionEvent;
  activeForegroundExecution: ActiveForegroundExecutionState | undefined;
  appendEvent: (event: SessionEvent, traceContext: TraceContext) => Promise<void>;
  startTargetTurnAccounting: (input: { inputID: string; startedAtMs: number; startedTarget: SessionGoal | null; traceContext: TraceContext; }) => Promise<SessionGoal | null>;
  sessionStore: SessionStorePort;
  trackResidencyBlockingWork: <T>(work: Promise<T>) => Promise<T>;
  heartbeatTargetTurnAccounting: (input: { inputID: string; seenAtMs: number; startedTarget: SessionGoal | null; traceContext: TraceContext; }) => Promise<void>;
  runUserPromptSubmitHooks: (prompt: string, attachments: TurnAttachment[] | undefined, traceContext: TraceContext, signal?: AbortSignal | undefined) => Promise<HookRunResult>;
  messageHistory: MessageHistory;
  rebuildProjection: () => Promise<SessionProjection>;
  accountTargetTurnCompletion: (input: { inputID: string; startedAtMs: number; startedTarget: SessionGoal | null; traceContext: TraceContext; usage?: ModelUsageSummary | undefined; }) => Promise<void>;
  artifactStore: ToolArtifactStorePort | undefined;
  fileSystemPort: FileSystemPort | undefined;
  imageProcessorPort: ImageProcessorPort | undefined;
  workingDirectory: string;
  persistPendingModelChangeTimeline: (traceContext: TraceContext) => Promise<void>;
  persistSyntheticUserNoticeForSession: (options: { messageID: MessageId; sessionId: SessionId; source: "subagent" | "background_task" | "fork" | "goal_state_change" | "goal-continuation" | "plugin_reference" | "rewind" | "selection_side_chat" | "subagent_message" | "todo_reminder" | "workflow_launch" | "shared_context"; text: string; traceContext: TraceContext; metadata?: Record<string, unknown> | undefined; visibility?: "user-visible" | "model-only" | undefined; }) => Promise<void>;
  persistUserPrompt: (messageID: MessageId, input: string, attachments: ResolvedTurnAttachment[] | undefined, traceContext: TraceContext, options?: { steerDelivery?: "queue" | "guide" | undefined; inputPresentation?: "task_notification" | "user_steer" | "coordinator_steer" | "coordinator_input" | "subagent_reply_steer" | "subagent_reply" | "task_notification_steer" | undefined; sessionInputId?: string | undefined; sourceCommandId?: string | undefined; clientId?: string | undefined; intent?: TurnInputIntentMetadata | undefined; executionKind?: TurnExecutionKind | undefined; epilogueStart?: number | undefined; } | undefined) => Promise<void>;
  injectPluginReferenceReminderFromTurn: (userInput: string, traceContext: TraceContext, toolDisallowlist?: readonly string[] | undefined) => Promise<void>;
  finishTargetTurnAccounting: (input: { inputID: string; endedAtMs: number; startedTarget: SessionGoal | null; status?: "paused" | undefined; traceContext: TraceContext; }) => Promise<SessionGoal | null>;
  pauseActiveTargetForCancellation: (traceContext: TraceContext) => Promise<void>;
  fallbackPendingGuidesToQueue: (options: { activeTurn: ActiveTurnSteeringState; events?: SessionEvent[] | undefined; reasonCode: "guide.noToolBoundary" | "guide.turnInterrupted"; traceContext: TraceContext; }) => Promise<number>;
  queueAutoDrain: boolean;
  queueExternalDrainActive: boolean;
  releaseTurnStart: (turnId: TurnId) => void;
  finishActiveTurn: (activeTurn: ActiveTurnSteeringState | undefined) => void;
  browserControlPort: BrowserControlPort | undefined;
  now: () => Date;
  lastEmittedLocalDate: string | undefined;
}
