// Original import types/overloads are authoritative; no substitute implementations.
export declare const buildDesktopProfileEnvironment:typeof import("./desktopProfile.js").buildDesktopProfileEnvironment;
export declare const existsSync:typeof import("node:fs").existsSync;
export declare const readFileSync:typeof import("node:fs").readFileSync;
export declare const homedir:typeof import("node:os").homedir;
export declare const join:typeof import("node:path").join;
export declare const resolve:typeof import("node:path").resolve;
export declare const win32:typeof import("node:path").win32;
export declare const listSSHConfigAliasesFromLocalConfig:typeof import("@knorvia/services/node").listSSHConfigAliasesFromLocalConfig;
export declare const getAppConfigDir:typeof import("@knorvia/services/node").getAppConfigDir;
export declare const getDataBaseDir:typeof import("@knorvia/services/node").getDataBaseDir;
export declare const KNORVIA_CUA_BUNDLED_HELPER_APP_PATH_ENV:typeof import("@knorvia/services/node").KNORVIA_CUA_BUNDLED_HELPER_APP_PATH_ENV;
export declare const KNORVIA_WINDOWS_APP_INSTALL_DIR_ENV:typeof import("@knorvia/services/node").KNORVIA_WINDOWS_APP_INSTALL_DIR_ENV;
export declare const DEV_HELPER_APP_NAME:typeof import("@knorvia/cua/broker/helperConstants").DEV_HELPER_APP_NAME;
export declare const HELPER_APP_NAME:typeof import("@knorvia/cua/broker/helperConstants").HELPER_APP_NAME;
export declare const KNORVIA_APP_VERSION_ENV:typeof import("@knorvia/shared").KNORVIA_APP_VERSION_ENV;
export declare const KNORVIA_AGENT_RUNTIME:typeof import("@knorvia/shared").KNORVIA_AGENT_RUNTIME;
export declare const KNORVIA_DYNAMIC_WORKFLOW_MODE_ENV:typeof import("@knorvia/shared").KNORVIA_DYNAMIC_WORKFLOW_MODE_ENV;
export declare const KNORVIA_ENV:typeof import("@knorvia/shared").KNORVIA_ENV;
export declare const KNORVIA_PRODUCT_FLAVOR:typeof import("@knorvia/shared").KNORVIA_PRODUCT_FLAVOR;
export declare const KNORVIA_RUNTIME_ENV_KEY:typeof import("@knorvia/shared").KNORVIA_RUNTIME_ENV_KEY;
export declare const KNORVIA_VERSION:typeof import("@knorvia/shared").KNORVIA_VERSION;
export declare const buildKnorviaToolEnvPassthroughEnv:typeof import("@knorvia/shared").buildKnorviaToolEnvPassthroughEnv;
export declare const normalizeDynamicWorkflowMode:typeof import("@knorvia/shared").normalizeDynamicWorkflowMode;
export declare const sanitizeKnorviaRuntimeEnv:typeof import("@knorvia/shared").sanitizeKnorviaRuntimeEnv;
export declare const resolvePlatformKeyForPackagedApp:typeof import("../../scripts/target-platform.mjs").resolvePlatformKeyForPackagedApp;
export declare const resolveRemoteCdnBaseUrls:typeof import("./remoteCdn.js").resolveRemoteCdnBaseUrls;
export declare const getElectronAppPath:typeof import("./desktopElectronApp.js").getElectronAppPath;
export declare const isElectronAppPackaged:typeof import("./desktopElectronApp.js").isElectronAppPackaged;
export declare const X509Certificate:typeof import("node:crypto").X509Certificate;
export declare const EMBEDDED_BROWSER_PARTITION:typeof import("./browserDataManager.js").EMBEDDED_BROWSER_PARTITION;
export declare const isDockerAvailable:typeof import("@knorvia/server/remote").isDockerAvailable;
export declare const listWSLDistros:typeof import("@knorvia/server/remote").listWSLDistros;
export declare const listDockerContainers:typeof import("@knorvia/server/remote").listDockerContainers;
export type ConnectOptions=import("@knorvia/server/remote").ConnectOptions;
export type ProxyConfig=import("electron").ProxyConfig;
export type Session=import("electron").Session;
export type KnorviaRuntimeEnv=import("@knorvia/shared").KnorviaRuntimeEnv;
export type ResolveRemoteCdnOptions=import("./remoteCdn.js").ResolveRemoteCdnOptions;
export declare const URL:typeof globalThis.URL;
export type Process=NodeJS.Process;
// No live process/env/resources/cwd/homedir snapshot is supplied. Native type only.
