import type { ConnectOptions } from "@knorvia/server/remote";
import { type KnorviaRuntimeEnv } from "@knorvia/shared";
import { type ResolveRemoteCdnOptions } from "./remoteCdn.js";
export declare const desktopRuntimeEnv: KnorviaRuntimeEnv;
export declare const runtimeApplicationName = "Knorvia Studio";
export declare const runtimeHomePath: any;
export declare const shouldUseElectronDefaultUserDataPath = false;
export declare const runtimeUserDataPath: any;
export declare const runtimeSessionDataPath: any;
export declare const hostModulePath: any;
export declare const schedulerModulePath: any;
export declare function getCredentialsDir(): any;
export type RemoteAssetDirs = Pick<ConnectOptions, "mockCdnDir" | "remoteCdnBaseUrl" | "remoteCdnBaseUrls" | "remoteCacheDir">;
type LocalRuntimeEnv = Record<string, string | undefined>;
export declare function isDockerDaemonAvailable(): Promise<boolean>;
export declare function listAvailableWSLDistros(): unknown;
export declare function listAvailableDockerContainers(): unknown;
export declare function listSSHConfigAliases(): unknown;
export declare function loadHostProcessEnvFromLocalFiles(): Record<string, string>;
export declare function resolveRemoteAssetDirs(options?: ResolveRemoteCdnOptions, localEnv?: LocalRuntimeEnv): RemoteAssetDirs;
export declare function resolveBundledAgentBinaryPath(): string | undefined;
export declare function buildHostProcessEnv(hostProcessLocalEnv: Record<string, string>): any;
export {};
