import { type BackgroundExecutionSnapshot, type DynamicWorkflowRunSnapshot, type SubagentTaskSnapshot, type SessionEvent, type TraceContext, type TurnId, type WorkflowTaskSnapshot } from "@knorvia/contracts";
import type { ExecutableToolCall } from "../types.js";
import type { ToolExecutorDeps } from "./types.js";
export type TaskSnapshot = BackgroundExecutionSnapshot | SubagentTaskSnapshot | WorkflowTaskSnapshot | DynamicWorkflowRunSnapshot;
export declare function hasSnapshotProvider(deps: ToolExecutorDeps, name: string): boolean;
export declare function hasDirectWaiter(deps: ToolExecutorDeps, name: string): boolean;
export declare function readTaskSnapshot(deps: ToolExecutorDeps, name: string, taskId: string): Promise<TaskSnapshot | undefined>;
export declare function waitForTaskSnapshot(deps: ToolExecutorDeps, name: string, taskId: string): Promise<TaskSnapshot | undefined>;
export declare function field(snapshot: object | undefined, key: string): unknown;
export declare function stringField(value: object | undefined, key: string): string | undefined;
export declare function snapshotString(snapshot: object | undefined, key: string): string | undefined;
export declare function workflowSubject(call: ExecutableToolCall, taskId: string, snapshot?: TaskSnapshot, launch?: Record<string, unknown>): string;
export declare function errorMessage(error: unknown): string;
export declare function runningSignature(snapshot: TaskSnapshot): string;
export declare function taskPayload(deps: ToolExecutorDeps, call: ExecutableToolCall, taskId: string, status: string, launch: Record<string, unknown>, snapshot?: TaskSnapshot): {
    taskId: string;
    toolCallId: string;
    toolName: string;
    taskKind: string;
    childSessionId: string | undefined;
    cancellable: boolean;
    command: string | undefined;
    description: unknown;
    status: string;
    pid: unknown;
    startedAt: Date | undefined;
    completedAt: Date | undefined;
    outputPath: string | undefined;
    stderrPersistedOutputPath: string | undefined;
    stdoutPersistedOutputPath: string | undefined;
    outputBytes: number | undefined;
    outputTruncated: boolean | undefined;
    outputTail: string | undefined;
    stderrBytes: number | undefined;
    stderrTail: string | undefined;
    stdoutBytes: number | undefined;
    stdoutTail: string | undefined;
    terminalId: string;
};
export declare function emitBackgroundTaskEvent(deps: ToolExecutorDeps, type: SessionEvent["type"], payload: Record<string, unknown>, traceContext: TraceContext, turnId: TurnId | undefined): Promise<void>;
//# sourceMappingURL=background-tracker-projection.d.ts.map