// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Knorvia Studio contributors

export const TARGET_MODULES = [
  "anthropic-reasoning-metadata",
  "anthropic-request-metadata",
  "anthropic-stream-compat",
  "empty-completion-retry",
  "errors",
  "failure-ai-sdk-provider-error",
  "failure-classifier",
  "failure-inspection",
  "failure-provider-business-codes",
  "failure-tls",
  "index",
  "media-transform-policy",
  "model-execution",
  "model-option-map-fetch",
  "model-request-headers",
  "model",
  "offpeak-retry",
  "openai-responses-json-compat",
  "opencode-session",
  "provider-finish-business-error",
  "reasoning-history-normalization",
  "request-admission",
  "retry-budget",
  "retry-policy",
  "runner-attribution",
  "runner-debug-redaction",
  "runner-debug",
  "runner-diagnostics",
  "runner-generate",
  "runner-network-headers",
  "runner-normalization",
  "runner-options",
  "runner-record",
  "runner-retry",
  "runner-runtime-headers",
  "runner-runtime",
  "runner-status",
  "runner-stream",
  "runner-telemetry",
  "runner",
  "stream-idle-timeout",
  "stream-retry-boundary",
  "streaming-tool-call-assembler",
  "strict-tool-schema",
  "system-message-compat",
  "tool-call-validation",
  "tool-input-normalization",
  "tool-result-media-projection",
  "tool-transform",
  "transform",
  "workflow-model-failure-policy",
] as const;

export type TargetModuleName = (typeof TARGET_MODULES)[number];
